module Shared.StaticData


let possibleTags = [ "Railroad"; "Steel"; "Canning" ]
let positibleCategories = [ "Railroad"; "Steel"; "Canning" ]
let positnleNeighborhoods =
    [
    "Arlington"
    "Central Park Heights"
    "Cheswolde"
    "Coldspring"
    "Cross Country"
    "Cylburn"
    "Fallstaff"
    "Glen"
    "Greenspring"
    "Langston Hughes"
    "Levindale"
    "Lucille Park"
    "Mount Washington"
    "Park Circle"
    "Parklane"
    "Pimlico Good Neighbors"
    "Reisterstown Station"
    "Seton Business Park"
    "Towanda-Grantley"
    "Woodmere"
    "Abell"
    "Barclay"
    "Bellona-Gittings"
    "Belvedere"
    "Better Waverly"
    "Blythewood"
    "Cameron Village"
    "Cedarcroft"
    "Charles North"
    "Chinquapin Park"
    "Cross Keys"
    "Ednor Gardens-Lakeside"
    "Evergreen"
    "Evesham Park"
    "Glen Oaks"
    "Greenmount West"
    "Guilford"
    "Hampden"
    "Harwood"
    "Homeland"
    "Hoes Heights"
    "Idlewood"
    "Johns Hopkins Homewood"
    "Jones Falls Area"
    "Kenilworth Park"
    "Kernewood"
    "Keswick"
    "Lake Evesham"
    "Lake Walker"
    "Loyola/Notre Dame"
    "Mid-Govans"
    "North Roland Park/Poplar Hill"
    "Oakenshawe"
    "Old Goucher"
    "The Orchards"
    "Original Northwood"
    "Pen Lucy"
    "Radnor-Winston"
    "Ramblewood"
    "Remington"
    "Richnor Springs"
    "Roland Park"
    "Rosebank"
    "Sabina-Mattfeldt"
    "Tuscany-Canterbury"
    "Villages at Homeland"
    "Waverly"
    "Wilson Park"
    "Winston-Govans"
    "Woodbourne Heights"
    "Woodbourne-McCabe"
    "Woodbury"
    "Wrenlane"
    "Wyman Park"
    "Wyndhurst"
    "York-Homeland"
    "Arcadia"
    "Armistead Gardens"
    "Bayview"
    "Belair-Parkside"
    "Belair-Edison"
    "Beverly Hills"
    "Broening Manor"
    "Cedmont"
    "Cedonia"
    "Clifton Park"
    "Coldstream Homestead Montebello"
    "Eastwood"
    "Four By Four"
    "Frankford"
    "Glenham-Belhar"
    "Graceland Park"
    "Greektown"
    "Hamilton Hills"
    "Herring Run"
    "Hillen"
    "Holabird Industrial Park"
    "Hopkins Bayview"
    "Kresson"
    "Lauraville"
    "Loch Raven"
    "Lower Herring Run Park"
    "Medford"
    "Montebello"
    "Moravia-Walther"
    "Morgan Park"
    "Morgan State University"
    "Mt Pleasant Park"
    "North Harford Road"
    "O'Donnell Heights"
    "Orangeville"
    "Orangeville Industrial Area"
    "Orchard Ridge"
    "Overlea"
    "Perring Loch"
    "Pulaski Industrial Area"
    "Rosemont"
    "Saint Helena"
    "Stonewood-Pentwood-Winston"
    "Taylor Heights"
    "Waltherson"
    "Westfield"
    "Baltimore Highlands"
    "Berea"
    "Biddle Street"
    "Brewers Hill"
    "Broadway East"
    "Butcher's Hill"
    "Canton"
    "Canton Industrial Area"
    "CARE"
    "Darley Park"
    "Downtown"
    "Downtown West"
    "Dundalk Marine Terminal"
    "East Baltimore Midway"
    "Ellwood Park/Monument"
    "Greenmount Cemetery"
    "Highlandtown"
    "Inner Harbor"
    "Johnston Square"
    "Madison-Eastend"
    "McElderry Park"
    "Milton-Montford"
    "Oliver"
    "Patterson Park"
    "Patterson Park Neighborhood"
    "Patterson Place"
    "South Clifton Park"
    "University of Maryland"
    "Mid-Town Belvedere"
    "Mount Vernon"
    "Seton Hill"
    "Dunbar-Broadway"
    "Fells Point"
    "Gay Street"
    "Jonestown"
    "Little Italy"
    "Middle East"
    "Oldtown"
    "Penn-Fallsway"
    "Perkins Homes"
    "Pleasant View Gardens"
    "Upper Fells Point"
    "Washington Hill"
    "Barre Circle"
    "Brooklyn"
    "Caroll Park"
    "Carroll-Camden Industrial Area"
    "Cherry Hill"
    "Curtis Bay"
    "Curtis Bay Industrial Area"
    "Fairfield Area"
    "Federal Hill"
    "Franklin Square"
    "Hawkins Point"
    "Hollins Market"
    "Lakeland"
    "Locust Point"
    "Locust Point Industrial Area"
    "Middle-Branch/Reedbird Parks"
    "Mount Winans"
    "New Southwest/Mount Clare"
    "Otterbein"
    "Poppleton"
    "Port Covington"
    "Ridgely's Delight"
    "Riverside"
    "Saint Paul"
    "Sharp-Leadenhall"
    "Spring Garden Industrial Area"
    "South Baltimore"
    "Stadium Area"
    "Union Square"
    "Washington Village/Pigtown"
    "Westport"
    "Allendale"
    "Beechfield"
    "Boyd Booth"
    "Carroll-South Hilton"
    "Carrollton Ridge"
    "Dickeyville"
    "Edgewood"
    "Edmondson Village"
    "Franklintown"
    "Gwynns Falls"
    "Gwynns Falls/Leakin Park"
    "Hunting Ridge"
    "Irvington"
    "Lower Edmondson Village"
    "Millhill"
    "Morrell Park"
    "Oaklee"
    "Penrose/Fayette Street Outreach"
    "Rognel Heights"
    "Saint Agnes"
    "Saint Josephs"
    "Shipley Hill"
    "Ten Hills"
    "Tremont"
    "Uplands"
    "Violetville"
    "Wakefield"
    "Westgate"
    "West Hills"
    "Wilhelm Park"
    "Yale-Heights"
    "Ashburton"
    "Bolton Hill"
    "Bridgeview-Greenlawn"
    "Burleight-Leighton"
    "Callaway-Garrison"
    "Central Forest Park"
    "Coppin Heights/Ash-Co-East"
    "Concerned Citizens of Forest Park"
    "Dolfield"
    "Dorchester"
    "Druid Heights"
    "Druid Hill Park"
    "East Arlington"
    "Easterwood"
    "Evergreen Lawn"
    "Fairmont"
    "Forest Park"
    "Forest Park Golf Course"
    "Franklintown Road"
    "Garwyn Oaks"
    "Grove Park"
    "Harlem Park"
    "Heritage Crossing"
    "Hanlon Longwood"
    "Howard Park"
    "Liberty Square"
    "Madison Park"
    "Midtown-Edmondson"
    "Mondawmin"
    "Mosher"
    "Mount Holly"
    "Northwest Community Action"
    "Panway/Braddish Avenue"
    "Parkview/Woodbrook"
    "Penn North"
    "Purnell"
    "Reservoir Hill"
    "Rosemont"
    "Rosemont Homeowners/Tenants"
    "Sandtown-Winchester"
    "Upton"
    "Walbrook"
    "West Arlington"
    "West Forest Park"
    "Winchester"
    "Windsor Hills"
    ]